#pragma once

#define VOID "void"
#define INT8 "int8"
#define INT16 "int16"
#define INT32 "int32"
#define INT64 "int64"
#define UINT8 "uint8"
#define UINT16 "uint16"
#define UINT32 "uint32"
#define UINT64 "uint64"
#define FLOAT "float"
#define DOUBLE "double"
#define BOOL "bool"
#define STRING "string"
#define CHAR "char"
#define UCHAR "uchar"
#define POINTER "pointer"
#define ARRAY "array"